services:
  frontend:
    container_name: app
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    develop:
      watch:
        - action: sync
          path: ../../src
          target: /app/src

        - action: sync
          path: ../../public
          target: /app/public

        - action: sync
          path: ../../index.html
          target: /app/index.html

        - action: rebuild
          path: ../../package.json

        - action: rebuild
          path: ../../yarn.lock

        - action: sync+restart
          path: ../../vite.config.ts
          target: /app/vite.config.ts

        - action: sync+restart
          path: ../../tsconfig.json
          target: /app/tsconfig.json
          
        - action: sync+restart
          path: ../../tailwind.config.js
          target: /app/tailwind.config.js
    ports:
      - 3001:3000