services:
  backend:
    container_name: backend
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.backend
    develop:
      watch:
        - action: sync
          path: ../../backend/src
          target: /backend/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ../../backend/package.json

  frontend:
    container_name: frontend
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.frontend
    develop:
      watch:
        - action: sync
          path: ../../frontend/src
          target: /frontend/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ../../frontend/package.json
    ports:
      - 3001:3000
