services:
  frontend:
    container_name: app
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    develop:
      watch:
        - action: sync
          path: ../../src
          target: ./src
          ignore:
            - node_modules/
        - action: sync
          path: ../../public
          target: ./public
        - action: rebuild
          path: ../../package.json
    ports:
      - 3001:3000