FROM node:18-alpine

COPY /backend .

RUN apk --no-cache add curl
RUN yarn install

RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
RUN chmod a+rx /usr/local/bin/yt-dlp

EXPOSE 9090

CMD ["node", "app.js"]