services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: frontend

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"
