services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile.backend
    x-develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /backend/src
          ignore:
            - node_modules/

  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile.frontend
    x-develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /frontend/src
          ignore:
            - node_modules/
    ports:
      - 3001:3000
