FROM node:16-alpine

COPY /backend .

# Python and FFmpeg are used by youtube-dl-exec
RUN apk add --no-cache python3
RUN apk add  --no-cache ffmpeg

RUN yarn install
RUN npx tsc

CMD ["node", "dist/app.js"]