services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - certbot_webroot_path:/var/www/certbot:ro
      - ssl_certificate:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../build:/usr/share/nginx/html:ro
      - ../../public/game:/game:ro
      - ../../ffmpeg_wasm:/ffmpeg_wasm
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - certbot_webroot_path:/var/www/certbot:rw   
      - ssl_certificate:/etc/letsencrypt:rw 

volumes:
  certbot_webroot_path:
  ssl_certificate: